[package]
name = "executor-async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3"

[dependencies.async-std]
version = "1.7.0"
features = ["attributes", "unstable"]